import nodemailer from "nodemailer";
import { config } from "../config.ts";
import { log } from "../util/log.ts";
import { sendIMessage, isIMessageConfigured } from "./imessage.ts";
import type { NewsSnapshot, NewsItem, NewsCategory } from "../../shared/types.ts";

/** 뉴스 다이제스트 iMessage 텍스트: 총건수 + 카테고리별 상위 2개 제목. */
export function newsIMessageText(s: NewsSnapshot): string {
  const total = s.categories.reduce((a, c) => a + c.items.length, 0);
  const lines = [`📰 뉴스 다이제스트 — ${s.date} (총 ${total}건)`];
  for (const c of s.categories) {
    if (!c.items.length) continue;
    const titles = c.items.slice(0, 2).map((it) => it.title).join(" / ");
    lines.push(`${c.emoji} ${c.label}(${c.items.length}): ${titles}`);
  }
  return lines.join("\n");
}

/** 뉴스 다이제스트를 본인 iMessage 로 발송. off/미설정/0건이면 false. 절대 throw 안 함. */
export async function sendNewsIMessage(s: NewsSnapshot): Promise<boolean> {
  if (!isIMessageConfigured()) return false;
  if (!s.categories.some((c) => c.items.length)) return false;
  try {
    await sendIMessage(newsIMessageText(s));
    return true;
  } catch (e) {
    log.warn(`뉴스 iMessage 발송 예외: ${(e as Error).message}`);
    return false;
  }
}

function escapeHtml(s: string): string {
  return (s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
function escapeAttr(s: string): string {
  return escapeHtml(s).replace(/'/g, "&#39;");
}

function relatedHtml(item: NewsItem): string {
  if (!item.related.length) return "";
  const links = item.related
    .map((r) => `<a href="${escapeAttr(r.link)}" style="color:#888;">${escapeHtml(r.label)}</a>`)
    .join(" · ");
  return `<p style="color:#888;font-size:12px;margin:8px 0 0 0;">관련 출처: ${links}</p>`;
}

function itemCard(item: NewsItem, color: string): string {
  const link = item.link
    ? `<a href="${escapeAttr(item.link)}" style="color:#4361ee;text-decoration:none;">🔗 원문 보기</a>`
    : "";
  return `<div style="margin-bottom:20px;padding:15px;background:#f8f9fa;border-radius:8px;border-left:4px solid ${color};">
  <h3 style="margin:0 0 8px 0;color:#1a1a2e;">${escapeHtml(item.title)}</h3>
  <p style="color:#888;font-size:12px;margin:0 0 8px 0;">출처: ${escapeHtml(item.source)} | 📅 ${escapeHtml(item.date)}</p>
  <p style="color:#333;line-height:1.6;margin:0 0 10px 0;">${escapeHtml(item.summary)}</p>
  ${link}
  ${relatedHtml(item)}
</div>`;
}

function sectionHtml(cat: NewsCategory): string {
  const head = `<h2 style="color:${cat.color};margin-top:40px;border-bottom:2px solid ${cat.color};padding-bottom:8px;">${cat.emoji} ${escapeHtml(cat.label)}</h2>`;
  const body = cat.items.length
    ? cat.items.map((it) => itemCard(it, cat.color)).join("")
    : `<p style="color:#999;padding:15px;background:#f8f9fa;border-radius:8px;">오늘은 해당 카테고리의 최신 뉴스가 없습니다.</p>`;
  return head + body;
}

/** 데일리 뉴스 다이제스트 이메일. NOTIFY_EMAIL + Gmail 자격증명 필요. */
export async function sendNewsEmail(s: NewsSnapshot): Promise<boolean> {
  if (!config.notify.email) return false;
  if (!config.notify.gmailAddress || !config.notify.gmailAppPassword) {
    log.warn("이메일 자격증명 미설정 → 뉴스 이메일 건너뜀");
    return false;
  }

  const sections = s.categories.map(sectionHtml).join("");

  const html = `<html><body style="font-family:'Apple SD Gothic Neo','Malgun Gothic',sans-serif;max-width:700px;margin:0 auto;padding:20px;background-color:#ffffff;">
  <h1 style="color:#1a1a2e;border-bottom:3px solid #4361ee;padding-bottom:10px;">📰 Daily News Digest</h1>
  <p style="color:#666;margin-bottom:10px;">${s.date} | 최근 24시간 뉴스만 수록</p>
  <p style="color:#888;font-size:13px;margin-bottom:30px;">🤖 AI · 🦾 로봇 · ⚛️ 양자컴퓨터 · 🇰🇷 국내 경제 · 🇺🇸 미국 · 🌍 세계 · 🆕 신제품 | 출처: WebSearch + GeekNews</p>
  ${sections}
  <hr style="margin-top:40px;border:none;border-top:1px solid #eee;">
  <p style="color:#999;font-size:11px;text-align:center;">Generated by Claude · Daily Dashboard | <a href="http://localhost:${config.port}">localhost:${config.port}</a></p>
</body></html>`;

  const transport = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 465,
    secure: true,
    auth: { user: config.notify.gmailAddress, pass: config.notify.gmailAppPassword },
  });
  await transport.sendMail({
    from: config.notify.gmailAddress,
    to: config.notify.gmailAddress,
    subject: `📰 Daily News Digest - ${s.date}`,
    html,
  });
  log.info("뉴스 이메일 발송 완료");
  return true;
}
