import nodemailer from "nodemailer";
import { config } from "../config.ts";
import { log } from "../util/log.ts";
import { sendIMessage, isIMessageConfigured } from "./imessage.ts";
import { escapeHtml, escapeAttr, safeHref } from "./html.ts";
import type { YoutubeSnapshot, YoutubeVideo, YoutubeCategory } from "../../shared/types.ts";

/** 유튜브 소식 iMessage 텍스트: 총건수 + 카테고리별 상위 2개 제목. */
export function youtubeIMessageText(s: YoutubeSnapshot): string {
  const total = s.categories.reduce((a, c) => a + c.items.length, 0);
  const lines = [`📺 유튜브 소식 — ${s.date} (총 ${total}건)`];
  for (const c of s.categories) {
    if (!c.items.length) continue;
    const titles = c.items.slice(0, 2).map((v) => v.title).join(" / ");
    lines.push(`${c.emoji} ${c.label}(${c.items.length}): ${titles}`);
  }
  return lines.join("\n");
}

/** 유튜브 소식을 본인 iMessage 로 발송. off/미설정/0건이면 false. 절대 throw 안 함. */
export async function sendYoutubeIMessage(s: YoutubeSnapshot): Promise<boolean> {
  if (!isIMessageConfigured()) return false;
  if (!s.categories.some((c) => c.items.length)) return false;
  try {
    await sendIMessage(youtubeIMessageText(s));
    return true;
  } catch (e) {
    log.warn(`유튜브 iMessage 발송 예외: ${(e as Error).message}`);
    return false;
  }
}

function metaLine(v: YoutubeVideo): string {
  const parts = [escapeHtml(v.channel)];
  if (v.channelHandle) parts.push(escapeHtml(v.channelHandle));
  parts.push(`📅 ${escapeHtml(v.date)}`);
  if (v.views) parts.push(`👁 ${escapeHtml(v.views)}`);
  if (v.duration) parts.push(`⏱ ${escapeHtml(v.duration)}`);
  return parts.join(" · ");
}

function videoCard(v: YoutubeVideo, color: string): string {
  // url·thumbnail 모두 LLM 이 만들어 온 값이라 http(s) 가 아니면 링크/이미지를 버린다.
  const href = safeHref(v.url);
  const thumbSrc = safeHref(v.thumbnail);
  const img = thumbSrc
    ? `<img src="${escapeAttr(thumbSrc)}" alt="" width="160" style="width:160px;border-radius:6px;display:block;" />`
    : "";
  const thumb =
    img && href
      ? `<a href="${escapeAttr(href)}" style="display:block;text-decoration:none;">
         ${img}
       </a>`
      : img;
  const watch = href
    ? `<a href="${escapeAttr(href)}" style="color:#ff0000;text-decoration:none;font-weight:600;">▶ 영상 보기</a>`
    : "";
  return `<div style="margin-bottom:18px;padding:14px;background:#f8f9fa;border-radius:8px;border-left:4px solid ${color};">
  <table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;"><tr>
    <td valign="top" style="padding-right:${thumb ? "12px" : "0"};">${thumb}</td>
    <td valign="top">
      <h3 style="margin:0 0 6px 0;color:#1a1a2e;font-size:15px;">${escapeHtml(v.title)}</h3>
      <p style="color:#888;font-size:12px;margin:0 0 8px 0;">${metaLine(v)}</p>
      <p style="color:#333;line-height:1.55;margin:0 0 8px 0;font-size:13px;">${escapeHtml(v.summary)}</p>
      ${watch}
    </td>
  </tr></table>
</div>`;
}

function sectionHtml(cat: YoutubeCategory): string {
  const head = `<h2 style="color:${cat.color};margin-top:36px;border-bottom:2px solid ${cat.color};padding-bottom:8px;">${cat.emoji} ${escapeHtml(cat.label)} <span style="font-size:13px;color:#999;font-weight:normal;">(${cat.items.length})</span></h2>`;
  const body = cat.items.length
    ? cat.items.map((v) => videoCard(v, cat.color)).join("")
    : `<p style="color:#999;padding:14px;background:#f8f9fa;border-radius:8px;">최근 새 영상이 없습니다.</p>`;
  return head + body;
}

/** 유튜브 소식 이메일 HTML. 순수 함수 — 발송하지 않는다. */
export function buildYoutubeEmailHtml(s: YoutubeSnapshot): string {
  const sections = s.categories.map(sectionHtml).join("");
  const catChips = s.categories.map((c) => `${c.emoji} ${escapeHtml(c.label)}`).join(" · ");

  return `<html><body style="font-family:'Apple SD Gothic Neo','Malgun Gothic',sans-serif;max-width:720px;margin:0 auto;padding:20px;background-color:#ffffff;">
  <h1 style="color:#1a1a2e;border-bottom:3px solid #ff0000;padding-bottom:10px;">▶ YouTube 소식</h1>
  <p style="color:#666;margin-bottom:10px;">${escapeHtml(s.date)} | 최근 ${s.freshDays}일 이내 영상</p>
  <p style="color:#888;font-size:13px;margin-bottom:24px;">${catChips} | 출처: YouTube (WebSearch/WebFetch 큐레이션)</p>
  ${sections}
  <hr style="margin-top:40px;border:none;border-top:1px solid #eee;">
  <p style="color:#999;font-size:11px;text-align:center;">Generated by Claude · Daily Dashboard | <a href="http://localhost:${config.port}">localhost:${config.port}</a></p>
</body></html>`;
}

/** 유튜브 소식 다이제스트 이메일. NOTIFY_EMAIL + Gmail 자격증명 필요. */
export async function sendYoutubeEmail(s: YoutubeSnapshot): Promise<boolean> {
  if (!config.notify.email) return false;
  if (!config.notify.gmailAddress || !config.notify.gmailAppPassword) {
    log.warn("이메일 자격증명 미설정 → 유튜브 이메일 건너뜀");
    return false;
  }

  const html = buildYoutubeEmailHtml(s);

  const transport = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 465,
    secure: true,
    auth: { user: config.notify.gmailAddress, pass: config.notify.gmailAppPassword },
  });
  await transport.sendMail({
    from: config.notify.gmailAddress,
    to: config.notify.gmailAddress,
    subject: `▶ YouTube 소식 - ${s.date}`,
    html,
  });
  log.info("유튜브 이메일 발송 완료");
  return true;
}
